name = "nexastream-api"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[vars]
FRONTEND_URL = "https://nexastream.org"
JWT_SECRET = "nexastream-jwt-secret-2026-production-change-me"

[[d1_databases]]
binding = "DB"
database_name = "nexastream-db"
database_id = "8dddb504b7b6fe324ab172381c499c06"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "nexastream-videos"
